// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provide

import (
	"log/slog"
	"net/http"
)

// Injectors from wire.go:

func InitializeServer(h slog.Handler) (http.Handler, func(), error) {
	client := NewClient()
	logger := NewSlog(h)
	mux := SetMux(h, client, logger)
	handler := NewHttpServer(mux)
	return handler, func() {
	}, nil
}
